<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api/client';
  import type { CollectorHealth } from '$lib/types/api';
  import StatePanel from '$lib/components/StatePanel.svelte';
  import StatusMark from '$lib/components/StatusMark.svelte';
  import { formatTime } from '$lib/utils/format';
  let items: CollectorHealth[] = [], loading = true, error = '';
  $: healthy = items.filter((item) => item.status === 'healthy').length;
  $: degraded = items.filter((item) => item.status === 'degraded' || item.status === 'unknown').length;
  $: offline = items.filter((item) => item.status === 'offline').length;
  async function load() { loading = true; error = ''; try { items = await api.collectors(); } catch (e) { error = e instanceof Error ? e.message : 'Unable to load collector health'; } finally { loading = false; } }
  onMount(load);
</script>

<svelte:head><title>Collector health · Temporal RCA</title></svelte:head>

<div class="page-heading"><div><span class="eyebrow">Collection plane</span><h1 class="display">Collector health</h1><p>Agent connectivity and signal pipeline readiness across the fleet.</p></div><button class="button" on:click={load} disabled={loading}>↻ Refresh status</button></div>

{#if loading}<StatePanel state="loading" title="Checking collection plane…" />{:else if error}<StatePanel state="error" message={error} retry={load} />{:else}
  <div class="health-summary"><div class="health-state"><span class="pulse" aria-hidden="true"></span><div><span class="eyebrow">Collection status</span><strong>{offline ? 'Attention required' : degraded ? 'Partial degradation' : 'All systems operational'}</strong><small>{items.length} collector reports · updated continuously</small></div></div><div class="health-counts"><span><b class="good">{healthy}</b><small>Healthy</small></span><span><b class="warn">{degraded}</b><small>Degraded</small></span><span><b class="bad">{offline}</b><small>Offline</small></span></div></div>
  {#if !items.length}<StatePanel state="empty" title="No collector reports" message="Status appears after the first agent heartbeat." />{:else}<section class="collectors panel"><header class="collectors-header"><div><span class="eyebrow">Signal pipeline</span><strong>Collector reports</strong></div><span class="mono count">{items.length} sources</span></header><div class="collector-list">{#each items as item (item.name + item.agent_id)}<article class="collector"><div class="collector-main"><StatusMark status={item.status} label={item.status === 'healthy' ? 'Healthy' : item.status === 'degraded' ? 'Degraded' : item.status === 'offline' ? 'Offline' : 'Unknown'} /><div class="collector-name"><h2>{item.name}</h2><span>{item.message || 'Operating normally'}</span></div></div><div class="collector-meta"><span><small>Agent</small><b class="mono">{item.agent_id ? item.agent_id.slice(0, 8) : 'Local'}</b></span><span><small>Spool</small><b class="mono">{item.spool_events ? `${item.spool_events.toLocaleString()} events` : 'Clear'}</b></span><time class="mono" datetime={item.updated_at}><small>Last report</small><b>{formatTime(item.updated_at)}</b></time></div></article>{/each}</div></section>{/if}
{/if}

<style>
  .page-heading { display:flex; align-items:end; justify-content:space-between; gap:20px; margin-bottom:19px; }.page-heading h1 { margin:5px 0 4px; font-size:40px; }.page-heading p { margin:0; color:var(--muted); font-size:13px; }.page-heading .button { min-height:34px; font-size:11px; }
  .health-summary { display:flex; align-items:center; justify-content:space-between; gap:20px; margin-bottom:11px; padding:15px 16px; border:1px solid rgba(34,197,94,.25); border-radius:7px; background:linear-gradient(110deg,rgba(34,197,94,.1),rgba(32,32,32,.6)); }.health-state { display:flex; align-items:center; gap:11px; }.health-state>div { display:flex; flex-direction:column; gap:3px; }.health-state strong { font-size:14px; }.health-state small { color:#7a8b99; font:10px 'IBM Plex Mono',monospace; }.pulse { width:10px; height:10px; flex:0 0 10px; border-radius:50%; background:var(--success); box-shadow:0 0 0 4px var(--success-soft),0 0 14px var(--success); }.health-counts { display:flex; gap:20px; }.health-counts span { display:flex; flex-direction:column; gap:3px; text-align:right; }.health-counts b { font:600 19px 'IBM Plex Mono',monospace; }.health-counts small { color:#748393; font:9px 'IBM Plex Mono',monospace; }.good { color:var(--success); }.warn { color:var(--amber); }.bad { color:var(--coral); }
  .collectors { overflow:hidden; }.collectors-header { min-height:57px; display:flex; align-items:center; justify-content:space-between; padding:10px 15px; border-bottom:1px solid var(--line); }.collectors-header>div { display:flex; flex-direction:column; gap:4px; }.collectors-header strong { font-size:12px; }.count { color:#8f8f8f; font-size:10px; }.collector { display:flex; justify-content:space-between; align-items:center; gap:20px; min-height:70px; padding:11px 15px; border-bottom:1px solid var(--line); }.collector:last-child { border-bottom:0; }.collector:hover { background:var(--surface-hover); }.collector-main { min-width:0; display:flex; align-items:center; gap:12px; }.collector-main :global(.status) { width:81px; flex-shrink:0; }.collector-name { min-width:0; display:flex; flex-direction:column; gap:4px; }.collector-name h2 { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; margin:0; font-size:12px; }.collector-name span { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; color:#798997; font-size:11px; }.collector-meta { display:flex; align-items:center; gap:21px; flex-shrink:0; }.collector-meta span,.collector-meta time { display:flex; flex-direction:column; align-items:flex-end; gap:4px; }.collector-meta small { color:#657482; font:9px 'IBM Plex Mono',monospace; text-transform:uppercase; }.collector-meta b { color:#b8c3cc; font-size:10px; font-weight:400; }.collector-meta time b { color:var(--cyan); }
  @media (max-width:780px) { .collector { align-items:flex-start; flex-direction:column; gap:11px; }.collector-meta { width:100%; justify-content:space-between; gap:10px; }.collector-meta span,.collector-meta time { align-items:flex-start; } } @media (max-width:600px) { .page-heading { align-items:flex-start; }.page-heading h1 { font-size:34px; }.page-heading p { line-height:1.45; }.health-summary { align-items:flex-start; flex-direction:column; gap:15px; }.health-counts { width:100%; justify-content:space-between; }.health-counts span { text-align:left; }.collector { padding:12px; }.collector-main { width:100%; }.collector-main :global(.status) { width:75px; }.collector-meta { flex-wrap:wrap; }.collector-meta time { margin-left:auto; } }
</style>
