<script lang="ts">
  import { onMount } from 'svelte';
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';
  import { api } from '$lib/api/client';
  import type { Entity, MetricSeries, TimelineEvent } from '$lib/types/api';
  import { correlationCursor } from '$lib/state/cursor';
  import { parseDashboardState, stateToSearch } from '$lib/state/url';
  import { dashboardNow } from '$lib/state/clock';
  import { formatMetric, formatRange, formatTime } from '$lib/utils/format';
  import MetricChart from '$lib/components/MetricChart.svelte';
  import ResourceTree from '$lib/components/ResourceTree.svelte';
  import StatePanel from '$lib/components/StatePanel.svelte';

  let entities: Entity[] = [], metrics: MetricSeries[] = [], events: TimelineEvent[] = [];
  let loading = true, error = '', filtersOpen = false, inspectorOpen = false, streamPickerOpen = false, showAllMetrics = false, mounted = false, loadedKey = '';
  $: state = parseDashboardState($page.url, $dashboardNow);
  $: selected = state.selected || '';
  $: selectedEntity = entities.find((entity) => entity.id === selected);
  $: selectedEvent = events.filter((event) => $correlationCursor != null && Math.abs(Date.parse(event.timestamp) - $correlationCursor) < 5000).sort((a, b) => Math.abs(Date.parse(a.timestamp) - ($correlationCursor || 0)) - Math.abs(Date.parse(b.timestamp) - ($correlationCursor || 0)))[0];
  $: chosenMetrics = state.streams.length ? metrics.filter((metric) => state.streams.includes(metric.id)) : metrics;
  $: visibleMetrics = state.streams.length || showAllMetrics ? chosenMetrics : chosenMetrics.slice(0, 8);
  $: queryKey = [selected, state.start.toISOString(), state.end.toISOString(), state.filters].join('|');
  $: metricGroups = ['system', 'process', 'application', 'dependency', 'other'].map((key) => ({ key, label: key === 'other' ? 'Other signals' : `${key[0].toUpperCase()}${key.slice(1)} signals`, items: metrics.filter((metric) => metric.source_type ? metric.source_type === key : metric.name.toLowerCase().startsWith(`system.`) ? key === 'system' : metric.name.toLowerCase().startsWith(`process.`) ? key === 'process' : metric.name.toLowerCase().startsWith(`dependency.`) ? key === 'dependency' : key === 'other') })).filter((group) => group.items.length);

  async function load() {
    loadedKey = queryKey; loading = true; error = '';
    try { entities = await api.entities(); const id = state.selected; if (id) [metrics, { items: events }] = await Promise.all([api.metrics(id, state.start.toISOString(), state.end.toISOString(), 800), api.events(state.start.toISOString(), state.end.toISOString(), state.filters)]); else { metrics = []; events = []; } }
    catch (e) { error = e instanceof Error ? e.message : 'Unable to build timeline'; }
    finally { loading = false; }
  }
  function navigate(next: typeof state) { goto(`/timeline?${stateToSearch(next)}`, { replaceState: true, keepFocus: true, noScroll: true }); }
  function choose(entity: Entity) { navigate({ ...state, selected: entity.id }); }
  function filter(value: string) { navigate({ ...state, filters: value }); }
  function toggleStream(id: string) { const streams = state.streams.includes(id) ? state.streams.filter((item) => item !== id) : [...state.streams, id]; navigate({ ...state, streams }); }
  function zoom(start: number, end: number) { navigate({ ...state, start: new Date(start), end: new Date(end), live: false }); }
  $: if (selectedEvent) inspectorOpen = true;
  $: if (mounted && queryKey !== loadedKey) load();
  onMount(() => { mounted = true; load(); });
</script>

<svelte:head><title>Signal timeline · Temporal RCA</title></svelte:head>

<div class="page-heading">
  <div><span class="eyebrow">Correlation workspace</span><h1 class="display">Signal timeline</h1><p>Trace infrastructure, services, processes and dependencies across one synchronized frame.</p></div>
  <div class="heading-actions"><span class="range mono">{formatRange(state.start, state.end, state.timezone)}</span><label class="search"><span class="sr-only">Filter telemetry</span><input value={state.filters} on:change={(event) => filter(event.currentTarget.value)} placeholder="Filter telemetry…" /></label><button class="button mobile" on:click={() => filtersOpen = !filtersOpen}>☷ Resources</button></div>
</div>

{#if loading}<StatePanel state="loading" title="Aligning signal lanes…" />{:else if error}<StatePanel state="error" message={error} retry={load} />{:else if !selectedEntity}<div class="selection-shell"><aside class="resources panel"><header><div><span class="eyebrow">Resource map</span><strong>Choose a signal source</strong></div></header><ResourceTree {entities} {selected} onSelect={choose} /></aside><StatePanel state="empty" title="Choose a resource" message="Nothing is selected automatically. Choose a node, service, process, container, or dependency to build its synchronized timeline." /></div>{:else}
  <div class="summary-row">
    <div class="summary-card"><span class="summary-icon">⌁</span><div><span class="eyebrow">Focus resource</span><strong>{selectedEntity.name}</strong><small>{selectedEntity.kind} · {selectedEntity.active ? 'reporting' : 'inactive'}</small></div></div>
    <div class="summary-card"><span class="summary-icon cyan">◌</span><div><span class="eyebrow">Visible lanes</span><strong>{visibleMetrics.length}<small class="muted-count"> / {metrics.length}</small></strong><small>{state.streams.length ? 'custom selection' : 'representative signals'}</small></div></div>
    <div class="summary-card"><span class="summary-icon amber">◆</span><div><span class="eyebrow">Events in frame</span><strong>{events.length}</strong><small>{events.filter((event) => event.signal_type === 'ground-truth').length} ground-truth intervals</small></div></div>
  </div>
  <div class="timeline-shell" class:inspecting={inspectorOpen}>
    <aside class="resources panel" class:open={filtersOpen}><header><div><span class="eyebrow">Resource map</span><strong>Choose a signal source</strong></div><button aria-label="Close resources" on:click={() => filtersOpen = false}>×</button></header><ResourceTree {entities} {selected} onSelect={choose} /></aside>
    <section class="tape panel">
      <header class="tape-head"><div><span class="eyebrow">Synchronized frame</span><strong>{selectedEntity.name}</strong></div><div class="cursor-time mono">{$correlationCursor ? formatTime($correlationCursor, state.timezone) : 'Move across a lane'}</div></header>
      <div class="stream-toolbar"><div><span class="eyebrow">Signal lanes</span><strong>{visibleMetrics.length} visible</strong></div><button class="button" class:active={streamPickerOpen} aria-expanded={streamPickerOpen} on:click={() => streamPickerOpen = !streamPickerOpen}>☷ Choose streams</button></div>
      {#if streamPickerOpen}<div class="stream-picker" aria-label="Choose metric streams">{#each metricGroups as group}<div class="stream-group"><span class="group-label">{group.label}</span>{#each group.items as metric}<label class="stream-option"><input type="checkbox" checked={state.streams.length ? state.streams.includes(metric.id) : visibleMetrics.some((item) => item.id === metric.id)} on:change={() => toggleStream(metric.id)} /><span>{metric.name}</span><small class="mono">{metric.unit}</small></label>{/each}</div>{/each}<p class="picker-note">Select specific lanes to override the representative eight-lane view.</p></div>{/if}
      {#if metrics.length === 0}<StatePanel state="empty" title="No metric lanes" message="This resource has no samples in the selected range." />{:else}
        {#each visibleMetrics as metric (metric.id)}<article class="lane"><div class="lane-label"><span class="eyebrow">{selectedEntity.kind}</span><b>{metric.name}</b><span class="mono">{formatMetric(metric.buckets.at(-1)?.last, metric.unit)}</span></div><div class="chart-wrap">{#key queryKey}<MetricChart series={metric} height={180} cursorTime={$correlationCursor} onRange={zoom} />{/key}</div></article>{/each}
        {#if !state.streams.length && !showAllMetrics && metrics.length > visibleMetrics.length}<button class="show-more" on:click={() => showAllMetrics = true}>Show all {metrics.length} signal lanes <span>↓</span></button>{/if}
      {/if}
      <article class="event-lane"><div class="lane-label"><span class="eyebrow">Signal history</span><b>Events &amp; lifecycle</b><span class="mono">{events.length} marks</span></div><div class="rail" role="group" aria-label="Logs, lifecycle events, and fault intervals">{#each events as event}<button class:fault={event.signal_type === 'ground-truth'} class:warn={event.severity === 'warning'} style={`left:${Math.max(0, Math.min(100, (Date.parse(event.timestamp) - state.start.getTime()) / (state.end.getTime() - state.start.getTime()) * 100))}%;width:${event.end_timestamp ? Math.max(4, (Date.parse(event.end_timestamp) - Date.parse(event.timestamp)) / (state.end.getTime() - state.start.getTime()) * 100) : 0.15}%`} aria-label={`${event.signal_type}: ${event.message} at ${formatTime(event.timestamp)}`} on:click={() => { $correlationCursor = Date.parse(event.timestamp); inspectorOpen = true; }}><span aria-hidden="true">{event.signal_type === 'ground-truth' ? '◆' : event.signal_type === 'lifecycle' ? '▲' : '|'}</span></button>{/each}</div></article>
    </section>
    <aside class="inspector panel" class:open={inspectorOpen}><header><div><span class="eyebrow">Frame inspector</span><strong>Correlated detail</strong></div><button aria-label="Close inspector" on:click={() => inspectorOpen = false}>×</button></header>{#if $correlationCursor}<time class="cursor-display mono">{formatTime($correlationCursor, state.timezone)}</time>{#if selectedEvent}<div class="event-type mono">{selectedEvent.signal_type} / {selectedEvent.severity || selectedEvent.type || 'event'}</div><h2>{selectedEvent.message}</h2><dl><dt>Event time</dt><dd>{formatTime(selectedEvent.timestamp, state.timezone)}</dd><dt>Ingestion delay</dt><dd>{selectedEvent.observed_timestamp ? `${Math.max(0, Date.parse(selectedEvent.observed_timestamp) - Date.parse(selectedEvent.timestamp))} ms` : '—'}</dd></dl>{:else}<p>No event within five seconds. Metric values remain aligned at the cursor.</p>{/if}{:else}<p>Select an event marker or move through a metric lane with the arrow keys.</p>{/if}</aside>
  </div>
{/if}

<style>
  .sr-only { position:absolute; width:1px; height:1px; overflow:hidden; clip:rect(0,0,0,0); }.page-heading { display:flex; justify-content:space-between; align-items:end; gap:20px; margin-bottom:18px; }.page-heading h1 { font-size:40px; margin:5px 0 4px; }.page-heading p { max-width:610px; margin:0; color:var(--muted); font-size:13px; line-height:1.45; }.heading-actions { display:flex; align-items:center; gap:8px; }.range { color:#7d8b99; font-size:10px; white-space:nowrap; }.search input { height:34px; width:220px; border:1px solid var(--line); border-radius:6px; padding:0 10px; background:var(--surface-raised); color:var(--text); font-size:11px; }.search input:focus { border-color:var(--brand-500); outline:0; box-shadow:0 0 0 3px rgba(255,255,255,.13); }.mobile { display:none; }.selection-shell{display:grid;grid-template-columns:280px minmax(0,1fr);gap:12px}.selection-shell>.resources{display:block}.selection-shell>.resources header{min-height:57px}
  .summary-row { display:grid; grid-template-columns:1.5fr 1fr 1fr; gap:9px; margin-bottom:10px; }.summary-card { min-width:0; display:flex; align-items:center; gap:10px; padding:12px 14px; border:1px solid var(--line); border-radius:7px; background:linear-gradient(135deg,rgba(32,32,32,.88),rgba(10,10,10,.93)); }.summary-card>div { min-width:0; display:flex; flex-direction:column; gap:3px; }.summary-card strong { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; font-size:13px; }.summary-card small { color:#8f8f8f; font:9px 'IBM Plex Mono',monospace; }.muted-count { color:#8f8f8f !important; font-size:10px !important; }.summary-icon { width:27px; height:27px; display:grid; place-items:center; flex:0 0 27px; border-radius:6px; color:var(--brand-300); background:var(--brand-soft); font:16px 'IBM Plex Mono',monospace; }.summary-icon.cyan { color:var(--cyan); background:var(--cyan-soft); }.summary-icon.amber { color:var(--amber); background:rgba(245,158,11,.1); }
  .timeline-shell { display:grid; grid-template-columns:240px minmax(440px,1fr) 0; gap:10px; }.timeline-shell.inspecting { grid-template-columns:240px minmax(440px,1fr) 290px; }.resources,.inspector,.tape { min-width:0; overflow:hidden; }.resources header,.inspector header { min-height:57px; display:flex; align-items:center; justify-content:space-between; gap:10px; padding:10px 13px; border-bottom:1px solid var(--line); }.resources header>div,.inspector header>div { display:flex; flex-direction:column; gap:4px; }.resources header strong,.inspector header strong { font-size:11px; }.resources header button,.inspector header button { width:24px; height:24px; border:1px solid transparent; border-radius:5px; color:var(--muted); background:transparent; font-size:18px; cursor:pointer; }.resources header button:hover,.inspector header button:hover { border-color:var(--line); color:var(--text); }.resources header button { display:none; }
  .tape-head { min-height:57px; display:flex; justify-content:space-between; align-items:center; gap:12px; padding:10px 14px; border-bottom:1px solid var(--line); }.tape-head>div:first-child { display:flex; flex-direction:column; gap:4px; }.tape-head strong { font-size:13px; }.cursor-time { color:var(--cyan); font-size:10px; }.stream-toolbar { display:flex; align-items:center; justify-content:space-between; gap:10px; padding:10px 14px; border-bottom:1px solid var(--line); }.stream-toolbar>div { display:flex; align-items:baseline; gap:9px; }.stream-toolbar strong { font-size:11px; }.stream-toolbar .button { min-height:28px; padding:3px 8px; font-size:10px; }.stream-toolbar .button.active { color:var(--brand-300); border-color:var(--brand-500); }.stream-picker { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:13px; padding:13px 14px; border-bottom:1px solid var(--line); background:rgba(8,8,8,.32); }.stream-group { display:flex; flex-direction:column; gap:5px; }.group-label { color:var(--muted); font:10px 'IBM Plex Mono',monospace; text-transform:uppercase; letter-spacing:.07em; }.stream-option { display:grid; grid-template-columns:14px minmax(0,1fr) auto; gap:6px; align-items:center; color:#b7c2cc; font-size:10px; }.stream-option input { accent-color:var(--brand-500); }.stream-option small { color:#71808f; font-size:8px; }.picker-note { grid-column:1/-1; margin:0; color:#71808f; font-size:10px; }
  .lane,.event-lane { display:grid; grid-template-columns:148px minmax(0,1fr); border-bottom:1px solid var(--line); }.lane-label { min-width:0; padding:11px 12px; border-right:1px solid var(--line); display:flex; flex-direction:column; gap:4px; }.lane-label b { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; font-size:10px; font-weight:600; }.lane-label>.mono { color:var(--cyan); font-size:10px; }.chart-wrap { min-width:0; padding:2px 8px 0; }.show-more { width:100%; min-height:37px; border:0; border-bottom:1px solid var(--line); color:var(--brand-300); background:rgba(255,255,255,.04); cursor:pointer; font-size:10px; }.show-more:hover { background:var(--brand-soft); }.show-more span { margin-left:5px; }.event-lane { min-height:94px; }.rail { position:relative; overflow:hidden; background:repeating-linear-gradient(90deg,transparent 0,transparent calc(10% - 1px),#252a30 10%); }.rail button { position:absolute; top:20%; height:60%; min-width:2px; border:0; padding:0; background:var(--cyan); color:var(--cyan); cursor:pointer; }.rail button span { position:absolute; top:-13px; left:-5px; }.rail button.warn { background:var(--amber); color:var(--amber); }.rail button.fault { min-width:4px; background:var(--coral); color:var(--coral); }
  .lane,.event-lane { grid-template-columns:190px minmax(0,1fr); }.lane-label { padding:16px; gap:7px; }.lane-label .eyebrow { font-size:13px; }.lane-label b { font-size:15px; }.lane-label>.mono { font-size:17px; font-weight:600; }.chart-wrap { padding:8px 12px 4px; }
  .inspector { display:none; padding-bottom:1rem; }.inspector.open { display:block; }.cursor-display { display:block; padding:16px 14px 5px; color:var(--cyan); font-size:24px; }.inspector p,.inspector h2,.inspector dl,.event-type { margin:10px 14px; }.inspector p { color:var(--muted); font-size:12px; line-height:1.6; }.event-type { color:var(--amber); font-size:9px; text-transform:uppercase; }.inspector h2 { font-size:14px; line-height:1.45; }.inspector dl { display:grid; grid-template-columns:1fr 1fr; gap:7px; font:10px 'IBM Plex Mono',monospace; }.inspector dt { color:#7e8a95; }.inspector dd { margin:0; text-align:right; color:#c0cad2; }
  @media (max-width:1050px) { .timeline-shell,.timeline-shell.inspecting { grid-template-columns:210px minmax(400px,1fr); }.inspector { position:fixed; z-index:60; right:0; top:60px; bottom:0; width:310px; background:var(--navy); box-shadow:-20px 0 40px rgba(0,0,0,.3); }.mobile { display:inline-flex; } }
  @media (max-width:760px) { .page-heading { align-items:flex-start; }.page-heading h1 { font-size:34px; }.page-heading p,.range { display:none; }.heading-actions { margin-top:4px; }.search { display:none; }.timeline-shell,.timeline-shell.inspecting { display:block; }.resources { display:none; position:fixed; z-index:65; inset:60px 0 0; border-radius:0; background:var(--navy); }.resources.open { display:block; }.resources header button { display:block; }.summary-row { grid-template-columns:1fr; }.summary-card { padding:10px 12px; }.stream-picker { grid-template-columns:1fr; }.lane,.event-lane { grid-template-columns:150px minmax(360px,1fr); overflow:auto; }.lane-label { padding:14px 12px; }.inspector { bottom:0; width:min(90vw,320px); }.tape-head { padding:9px 10px; }.stream-toolbar { padding:9px 10px; } }
</style>
