import{expect,test,type Page}from'@playwright/test';
const host={id:'host-01',name:'lab-producer-01',kind:'host',health:'healthy',active:true,last_seen:new Date().toISOString(),labels:{os:'Ubuntu 24.04',address:'10.20.0.11'},children:[]};
async function mockApi(page:Page){await page.route('**/api/v1/**',async route=>{const u=new URL(route.request().url()),now=new Date().toISOString();let json:unknown=[];if(u.pathname.endsWith('/topology'))json={hosts:[{...host,last_seen_at:now,attributes:host.labels}],services:[],processes:[],dependencies:[]};else if(u.pathname.endsWith('/hosts/host-01'))json={...host,last_seen_at:now,attributes:host.labels};else if(u.pathname.endsWith('/metrics/series'))json=[{id:1,name:'system.cpu.utilization',unit:'percent',host_id:'host-01'}];else if(u.pathname.endsWith('/metrics/query'))json={bucket_seconds:5,series:[{series_id:1,points:[{timestamp:new Date(Date.now()-5000).toISOString(),min:22,max:28,average:25,last:28,count:5},{timestamp:now,min:26,max:35,average:31,last:35,count:5}]}]};else if(u.pathname.endsWith('/events'))json=[{event_id:'evt-1',timestamp:now,observed_timestamp:now,signal_type:'ground-truth',message:'CPU pressure injected'}];else if(u.pathname.endsWith('/logs'))json={items:[],next_cursor:null};else if(u.pathname.endsWith('/experiments'))json=[{id:'exp-01',name:'Producer CPU pressure',status:'completed',configuration:{scenario:'cpu_pressure'},started_at:now}];else if(u.pathname.endsWith('/experiments/exp-01'))json={id:'exp-01',name:'Producer CPU pressure',status:'completed',configuration:{scenario:'cpu_pressure'},started_at:now};await route.fulfill({json});});}
test.beforeEach(async({page})=>{await mockApi(page)});
test('drills from fleet into a host and preserves timeline focus',async({page})=>{await page.goto('/');await expect(page.getByRole('heading',{name:'Fleet recorder'})).toBeVisible();await page.getByRole('link',{name:/lab-producer-01/}).click();await expect(page.getByRole('heading',{name:'lab-producer-01'})).toBeVisible();await page.getByRole('link',{name:/Open in timeline/}).click();await expect(page).toHaveURL(/selected=host-01/);await expect(page.getByText('system.cpu.utilization')).toBeVisible()});
test('shared presets remain live rolling ranges',async({page,isMobile})=>{test.skip(isMobile);await page.goto('/timeline?selected=host-01');await page.getByRole('button',{name:/last 15 minutes/i}).click();await expect(page).toHaveURL(/range=15/);await expect(page).not.toHaveURL(/live=false/);await expect(page.getByRole('button',{name:/last 15 minutes/i})).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('button',{name:/Return to live/})).toHaveCount(0);await page.getByRole('button',{name:/last hour/i}).click();await expect(page).toHaveURL(/range=60/);await expect(page.getByRole('button',{name:/last hour/i})).toHaveAttribute('aria-pressed','true')});
test('filters logs with shareable URL and shows fault markers',async({page})=>{await page.goto('/timeline?selected=host-01');const input=page.getByPlaceholder('Filter telemetry…');await input.fill('severity:error');await input.press('Tab');await expect(page).toHaveURL(/filters=severity%3Aerror/);await expect(page.getByRole('button',{name:/ground-truth/})).toBeVisible()});
test('responsive navigation remains available',async({page,isMobile})=>{test.skip(!isMobile);await page.goto('/');await expect(page.getByRole('navigation')).toBeVisible();await page.getByRole('link',{name:/Timeline/}).click();await expect(page.getByRole('heading',{name:'Signal timeline'})).toBeVisible()});
test('stable fleet visual',async({page,browserName})=>{test.skip(browserName!=='chromium');await page.goto('/');await expect(page).toHaveScreenshot('fleet.png',{animations:'disabled',maxDiffPixelRatio:.02})});
